"""
Public Unauthenticated Market Data Fetcher Module for Kuantra Terminal.
Provides zero-auth crypto and macro/forex market data retrieval.
"""

from .public_fetcher import PublicMarketDataFetcher, public_market_fetcher
from .binance_depth_sequence import (
    BinanceDepthSequenceValidator,
    DepthSequenceDecision,
    DepthSequenceResult,
    DepthSequenceState,
)
from .binance_depth_recovery import (
    BinanceDepthRecoveryCoordinator,
    DepthRecoveryDecision,
    DepthRecoveryResult,
    DepthRecoveryState,
)
from .binance_depth_payload import (
    BinanceDepthBook,
    DepthBookDecision,
    DepthBookResult,
    DepthLevel,
    DepthPayloadError,
    NormalizedDepthSnapshot,
    NormalizedDepthUpdate,
    normalize_snapshot,
    normalize_update,
)
from .market_event_envelope import (
    GENESIS_HASH,
    MARKET_EVENT_SCHEMA_VERSION,
    MarketEventChain,
    MarketEventEnvelope,
    MarketEventEnvelopeError,
    MarketEventIdentityConflict,
    envelope_from_dict,
    validate_market_event_envelope,
)
from .market_event_segment import (
    MarketEventSegmentRecoveryError,
    MarketEventSegmentWriter,
)
from .market_event_segments import (
    MANIFEST_SCHEMA_VERSION,
    MarketEventSegmentSet,
    MarketEventSegmentSetRecoveryError,
)
from .market_event_batch import (
    BATCH_SCHEMA_VERSION,
    MarketEventBatch,
    MarketEventBatchError,
    MarketEventBatchProjector,
)
from .binance_depth_ingestor import (
    BinanceDepthIngestor,
    DepthIngestDecision,
    DepthIngestResult,
    DepthIngestorState,
)
from .binance_depth_transport import (
    BinanceDepthTransport,
    BinanceDepthTransportConfig,
    DepthTransportDecision,
    DepthTransportResult,
)
from .binance_depth_network import (
    BinanceDepthEnvironment,
    BinanceDepthNetworkAdapter,
    BinanceDepthNetworkConfig,
    BinanceDepthNetworkError,
)
from .binance_depth_session import (
    BinanceDepthReconnectPolicy,
    BinanceDepthSession,
    DepthSessionDecision,
    DepthSessionResult,
)
from .binance_depth_soak import (
    BinanceDepthFixtureRunner,
    BinanceDepthSoakHarness,
    DepthFixtureCycle,
    DepthSoakReport,
)
from .binance_depth_fault_matrix import (
    FAULT_MATRIX_SCHEMA_VERSION,
    DepthFaultScenario,
    build_binance_depth_fault_matrix,
    run_binance_depth_fault_matrix,
    verify_binance_depth_fault_matrix,
)
from .binance_depth_report import (
    LEGACY_REPORT_SCHEMA_VERSION,
    REPORT_SCHEMA_VERSION,
    DepthSoakReportVerification,
    DepthSoakReportVerdict,
    verify_depth_soak_report,
)
from .binance_depth_report_archive import (
    ARCHIVE_SCHEMA_VERSION,
    BinanceDepthReportArchive,
    DepthSoakArchiveError,
    DepthSoakArchiveRecord,
)
from .binance_depth_attestation import (
    ATTESTATION_SCHEMA_VERSION,
    KEY_BUNDLE_SCHEMA_VERSION,
    BinanceDepthAttestationStore,
    DepthSoakAttestation,
    DepthSoakAttestationError,
    attest_archive_record,
    generate_operator_key_bundle,
    private_key_from_bundle,
    verify_attestation,
)
from .binance_depth_key_registry import (
    KEY_REGISTRY_SCHEMA_VERSION,
    AttestationKeyAudit,
    BinanceDepthAttestationKeyRegistry,
    DepthKeyRegistryError,
    OperatorKeyRecord,
    OperatorKeyStatus,
    key_id_for_public_key,
)
from .binance_depth_attestation_gate import (
    ATTESTATION_GATE_SCHEMA_VERSION,
    DEFAULT_MAX_AGE_SECONDS,
    DEFAULT_MAX_FUTURE_SKEW_SECONDS,
    DepthAttestationGateResult,
    evaluate_binance_depth_attestation_gate,
)
from .binance_depth_key_policy import (
    DEFAULT_MAX_ACTIVE_AGE_SECONDS,
    DEFAULT_MAX_ACTIVE_KEYS,
    DEFAULT_MAX_FUTURE_SKEW_SECONDS,
    DEFAULT_REVOKED_RETENTION_SECONDS,
    KEY_POLICY_SCHEMA_VERSION,
    KeyRotationPolicyResult,
    evaluate_key_rotation_policy,
)
from .binance_depth_review_record import (
    REVIEW_RECORD_SCHEMA_VERSION,
    BinanceDepthOperatorReviewStore,
    DepthOperatorReviewRecord,
    DepthReviewRecordError,
    create_operator_review_record,
    verify_operator_review_record,
)
from .binance_depth_evidence_bundle import (
    BUNDLE_MANIFEST_NAME,
    EVIDENCE_BUNDLE_SCHEMA_VERSION,
    DepthEvidenceBundleError,
    DepthEvidenceBundleManifest,
    DepthEvidenceBundleVerification,
    EvidenceBundleFile,
    create_evidence_bundle,
    restore_evidence_bundle,
    verify_evidence_bundle,
)

__all__ = [
    "PublicMarketDataFetcher",
    "public_market_fetcher",
    "BinanceDepthSequenceValidator",
    "DepthSequenceDecision",
    "DepthSequenceResult",
    "DepthSequenceState",
    "BinanceDepthRecoveryCoordinator",
    "DepthRecoveryDecision",
    "DepthRecoveryResult",
    "DepthRecoveryState",
    "BinanceDepthBook",
    "DepthBookDecision",
    "DepthBookResult",
    "DepthLevel",
    "DepthPayloadError",
    "NormalizedDepthSnapshot",
    "NormalizedDepthUpdate",
    "normalize_snapshot",
    "normalize_update",
    "GENESIS_HASH",
    "MARKET_EVENT_SCHEMA_VERSION",
    "MarketEventChain",
    "MarketEventEnvelope",
    "MarketEventEnvelopeError",
    "MarketEventIdentityConflict",
    "envelope_from_dict",
    "validate_market_event_envelope",
    "MarketEventSegmentRecoveryError",
    "MarketEventSegmentWriter",
    "MANIFEST_SCHEMA_VERSION",
    "MarketEventSegmentSet",
    "MarketEventSegmentSetRecoveryError",
    "BATCH_SCHEMA_VERSION",
    "MarketEventBatch",
    "MarketEventBatchError",
    "MarketEventBatchProjector",
    "BinanceDepthIngestor",
    "DepthIngestDecision",
    "DepthIngestResult",
    "DepthIngestorState",
    "BinanceDepthTransport",
    "BinanceDepthTransportConfig",
    "DepthTransportDecision",
    "DepthTransportResult",
    "BinanceDepthEnvironment",
    "BinanceDepthNetworkAdapter",
    "BinanceDepthNetworkConfig",
    "BinanceDepthNetworkError",
    "BinanceDepthReconnectPolicy",
    "BinanceDepthSession",
    "DepthSessionDecision",
    "DepthSessionResult",
    "BinanceDepthFixtureRunner",
    "BinanceDepthSoakHarness",
    "DepthFixtureCycle",
    "DepthSoakReport",
    "FAULT_MATRIX_SCHEMA_VERSION",
    "DepthFaultScenario",
    "build_binance_depth_fault_matrix",
    "run_binance_depth_fault_matrix",
    "verify_binance_depth_fault_matrix",
    "LEGACY_REPORT_SCHEMA_VERSION",
    "REPORT_SCHEMA_VERSION",
    "DepthSoakReportVerification",
    "DepthSoakReportVerdict",
    "verify_depth_soak_report",
    "ARCHIVE_SCHEMA_VERSION",
    "BinanceDepthReportArchive",
    "DepthSoakArchiveError",
    "DepthSoakArchiveRecord",
    "ATTESTATION_SCHEMA_VERSION",
    "KEY_BUNDLE_SCHEMA_VERSION",
    "BinanceDepthAttestationStore",
    "DepthSoakAttestation",
    "DepthSoakAttestationError",
    "attest_archive_record",
    "generate_operator_key_bundle",
    "private_key_from_bundle",
    "verify_attestation",
    "KEY_REGISTRY_SCHEMA_VERSION",
    "AttestationKeyAudit",
    "BinanceDepthAttestationKeyRegistry",
    "DepthKeyRegistryError",
    "OperatorKeyRecord",
    "OperatorKeyStatus",
    "key_id_for_public_key",
    "ATTESTATION_GATE_SCHEMA_VERSION",
    "DEFAULT_MAX_AGE_SECONDS",
    "DEFAULT_MAX_FUTURE_SKEW_SECONDS",
    "DepthAttestationGateResult",
    "evaluate_binance_depth_attestation_gate",
    "DEFAULT_MAX_ACTIVE_AGE_SECONDS",
    "DEFAULT_MAX_ACTIVE_KEYS",
    "DEFAULT_MAX_FUTURE_SKEW_SECONDS",
    "DEFAULT_REVOKED_RETENTION_SECONDS",
    "KEY_POLICY_SCHEMA_VERSION",
    "KeyRotationPolicyResult",
    "evaluate_key_rotation_policy",
    "REVIEW_RECORD_SCHEMA_VERSION",
    "BinanceDepthOperatorReviewStore",
    "DepthOperatorReviewRecord",
    "DepthReviewRecordError",
    "create_operator_review_record",
    "verify_operator_review_record",
    "BUNDLE_MANIFEST_NAME",
    "EVIDENCE_BUNDLE_SCHEMA_VERSION",
    "DepthEvidenceBundleError",
    "DepthEvidenceBundleManifest",
    "DepthEvidenceBundleVerification",
    "EvidenceBundleFile",
    "create_evidence_bundle",
    "restore_evidence_bundle",
    "verify_evidence_bundle",
]
