"""
TradingView HMAC-SHA256 Webhook & Cloudflare Tunnel Relay Receiver.
Securely verifies, parses, and ingests Pine Script alert signals into Kuantra Terminal.
"""

import hmac
import hashlib
import json
import math
import time
import logging
import os
import secrets
from datetime import datetime, timezone
from typing import Dict, Any, Optional, Literal
from pydantic import BaseModel, ConfigDict, Field, ValidationError, field_validator
from fastapi import APIRouter, Header, HTTPException, Request, Query
from app.db.repositories.evidence_ledger_repo import EvidenceLedgerRepository, canonical_json
from app.db.sqlite_driver import sqlite_driver
from app.db.sync_pipeline import sync_pipeline
from app.core.config import settings
from app.core.input_limits import MAX_WEBHOOK_BYTES

logger = logging.getLogger("webhook_tv")

webhook_router = APIRouter(tags=["Webhook"])
# The desktop integrations gateway mounts only the signed ingest route.  The
# observation review/confirm routes are UI-side actions and must never be
# exposed on the loopback gateway socket.
webhook_ingest_router = APIRouter(tags=["Webhook"])

# Never ship a shared/default secret. In development without explicit configuration,
# use a process-random value so requests fail across restarts; production deployments
# must provide KUANTRA_WEBHOOK_SECRET through an external secret store.
WEBHOOK_SECRET_CONFIGURED = bool(os.environ.get("KUANTRA_WEBHOOK_SECRET"))
WEBHOOK_SECRET_KEY = os.environ.get("KUANTRA_WEBHOOK_SECRET") or secrets.token_urlsafe(32)

class TradingViewSignalPayload(BaseModel):
    model_config = ConfigDict(extra="ignore", str_strip_whitespace=True)

    symbol: str = Field(..., min_length=1, max_length=64)
    action: str = Field(..., min_length=1, max_length=16)
    price: float = Field(..., gt=0, le=10**15)
    stop_loss: Optional[float] = Field(default=None, gt=0, le=10**15)
    take_profit: Optional[float] = Field(default=None, gt=0, le=10**15)
    qty: Optional[float] = Field(default=1.0, gt=0, le=10**12)
    strategy: Optional[str] = Field(default="PineScript_Alert", max_length=128)
    timeframe: Optional[str] = Field(default="15m", max_length=32)
    passphrase: Optional[str] = Field(default=None, max_length=512)
    timestamp: Optional[float] = Field(default=None, gt=0, le=10**12)

    @field_validator("action", mode="before")
    @classmethod
    def _normalize_action(cls, value: Any) -> str:
        action = str(value or "").strip().upper()
        if action not in {"BUY", "SELL", "LONG", "SHORT"}:
            raise ValueError("action must be BUY, SELL, LONG, or SHORT")
        return action

    @field_validator("strategy", "timeframe", "passphrase")
    @classmethod
    def _reject_control_text(cls, value: Optional[str]) -> Optional[str]:
        if value is not None and any(ord(character) < 32 for character in value):
            raise ValueError("text fields cannot contain control characters")
        return value


class TradingViewObservationConfirmPayload(BaseModel):
    """User-confirmed external fill data for a previously received alert."""

    entry_price: float = Field(..., gt=0, le=10**15)
    execution_venue: Optional[str] = Field(default=None, max_length=120)
    entry_time: Optional[str] = Field(default=None, min_length=1, max_length=64)
    notes: Optional[str] = Field(default=None, max_length=2000)

    @field_validator("execution_venue", "entry_time", "notes")
    @classmethod
    def _reject_control_text(cls, value: Optional[str]) -> Optional[str]:
        if value is not None and any(ord(character) < 32 for character in value):
            raise ValueError("text fields cannot contain control characters")
        cleaned = value.strip() if value is not None else None
        return cleaned or None

def _constant_time_equals(candidate: Any, expected: str) -> bool:
    """Type- and encoding-safe constant-time comparison."""
    try:
        return hmac.compare_digest(
            str(candidate or "").encode("utf-8"), str(expected).encode("utf-8")
        )
    except Exception:
        return False


async def _read_bounded_body(request: Request, limit: int = MAX_WEBHOOK_BYTES) -> bytes:
    """Stream the request body and abort as soon as the byte ceiling is exceeded."""
    chunks: list[bytes] = []
    total = 0
    async for chunk in request.stream():
        total += len(chunk)
        if total > limit:
            raise HTTPException(
                status_code=413,
                detail=f"Webhook body exceeds the safety size limit of {limit} bytes.",
            )
        chunks.append(chunk)
    return b"".join(chunks)


def verify_hmac_signature(raw_body: bytes, signature_header: Optional[str], secret: str = WEBHOOK_SECRET_KEY) -> bool:
    """Verifies HMAC-SHA256 signature generated by Cloudflare Worker or TradingView."""
    if not signature_header:
        return False
    expected = hmac.new(secret.encode("utf-8"), raw_body, hashlib.sha256).hexdigest()
    return _constant_time_equals(str(signature_header).strip().lower(), expected.lower())


def verify_passphrase(provided_passphrase: Optional[str], expected_secret: str = WEBHOOK_SECRET_KEY) -> bool:
    if not provided_passphrase or not isinstance(provided_passphrase, str):
        return False
    return _constant_time_equals(provided_passphrase, expected_secret)


def _timestamp_to_iso(timestamp: Optional[float]) -> str:
    if timestamp is None:
        return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
    seconds = float(timestamp)
    if seconds > 10**11:
        seconds /= 1000.0
    return datetime.fromtimestamp(seconds, timezone.utc).isoformat().replace("+00:00", "Z")


def _observation_from_event(
    event: Dict[str, Any],
    *,
    status: str = "PENDING_REVIEW",
    confirmation_event_id: Optional[str] = None,
) -> Optional[Dict[str, Any]]:
    payload = event.get("normalized_payload")
    if not isinstance(payload, dict):
        return None
    observation = payload.get("tradingview_observation")
    if not isinstance(observation, dict):
        return None
    result = {
        "observation_id": event.get("event_id"),
        "event_hash": event.get("event_hash"),
        "status": status,
        **observation,
    }
    if confirmation_event_id is not None:
        result["confirmation_event_id"] = confirmation_event_id
    return result

@webhook_ingest_router.post("/webhook/tradingview")
@webhook_router.post("/webhook/tradingview")
async def receive_tradingview_webhook(
    request: Request,
    x_tradingview_signature: Optional[str] = Header(None, alias="X-TradingView-Signature"),
    x_cf_tunnel_auth: Optional[str] = Header(None, alias="X-CF-Tunnel-Auth")
):
    content_length = request.headers.get("content-length")
    if content_length:
        try:
            if int(content_length) > MAX_WEBHOOK_BYTES:
                raise HTTPException(
                    status_code=413,
                    detail=f"Webhook body exceeds the safety size limit of {MAX_WEBHOOK_BYTES} bytes.",
                )
        except ValueError as exc:
            raise HTTPException(status_code=400, detail="Invalid Content-Length header") from exc

    raw_body = await _read_bounded_body(request)
    try:
        data = json.loads(raw_body.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise HTTPException(status_code=400, detail="Invalid UTF-8 JSON payload") from exc
    if not isinstance(data, dict):
        raise HTTPException(status_code=400, detail="Webhook JSON root must be an object")

    # Security check: verify via HMAC signature OR passphrase
    has_valid_hmac = verify_hmac_signature(raw_body, x_tradingview_signature)
    has_valid_passphrase = verify_passphrase(data.get("passphrase"))
    has_valid_tunnel = _constant_time_equals(x_cf_tunnel_auth, WEBHOOK_SECRET_KEY)

    if not (has_valid_hmac or has_valid_passphrase or has_valid_tunnel):
        logger.warning("[WEBHOOK] Unauthorized signal rejected (Invalid HMAC / Passphrase).")
        raise HTTPException(status_code=401, detail="Unauthorized: Invalid HMAC signature or passphrase")

    try:
        payload = TradingViewSignalPayload.model_validate(data)
    except ValidationError as exc:
        raise HTTPException(status_code=400, detail="Invalid TradingView signal payload") from exc

    if not all(
        math.isfinite(number)
        for number in (payload.price, payload.qty, payload.stop_loss, payload.take_profit, payload.timestamp)
        if number is not None
    ):
        raise HTTPException(status_code=400, detail="Signal numeric fields must be finite")

    # Preserve provider/venue identity such as OANDA:XAUUSD.  Removing the
    # separator would make an alert look like a different instrument.
    symbol = payload.symbol.strip().upper()
    if not symbol or len(symbol) > 64 or any(ord(character) < 32 for character in symbol):
        raise HTTPException(status_code=400, detail="Signal symbol is invalid")
    action = payload.action
    price = payload.price
    sl = payload.stop_loss
    tp = payload.take_profit
    qty = payload.qty or 1.0
    strategy = payload.strategy or "TradingView_Alert"

    logger.info(f"[WEBHOOK] Valid signal received: {action} {qty} {symbol} @ {price}")

    # A TradingView alert is a signal/observation, not proof of an external
    # fill.  Store a secret-free immutable review event and require explicit
    # confirmation before creating a journal trade snapshot.
    observation = {
        "symbol": symbol,
        "action": action,
        "price": price,
        "stop_loss": sl,
        "take_profit": tp,
        "qty": qty,
        "strategy": strategy,
        "timeframe": payload.timeframe or "15m",
        "timestamp": payload.timestamp,
        "observed_at": _timestamp_to_iso(payload.timestamp),
    }
    fingerprint = hashlib.sha256(canonical_json(observation).encode("utf-8")).hexdigest()
    event_id = f"TV-OBS-{fingerprint[:24]}"
    ledger = EvidenceLedgerRepository(sqlite_driver.db_path)
    event = ledger.append_event(
        event_type="JournalReviewAdded",
        account_id="local-journal",
        venue="tradingview",
        idempotency_key=f"tradingview-observation:{fingerprint}",
        normalized_payload={"tradingview_observation": observation},
        raw_payload={"tradingview_observation": observation},
        occurred_at=observation["observed_at"],
        schema_version="1",
        adapter_version="tradingview-webhook-v2",
        correlation_id=event_id,
        provenance={
            "source": "tradingview_webhook",
            "source_ref": strategy,
            "review_state": "PENDING_REVIEW",
            "price_origin": "TRADINGVIEW_ALERT",
        },
        event_id=event_id,
    )

    return {
        "status": "PENDING_REVIEW",
        "observation_id": event["event_id"],
        "created": event["created"],
        "symbol": symbol,
        "action": action,
        "price": price,
        "timestamp": time.time()
    }


@webhook_router.get("/tradingview/observations")
def list_tradingview_observations(
    limit: int = Query(50, ge=1, le=200),
):
    """List bounded TradingView alert observations awaiting user review."""
    ledger = EvidenceLedgerRepository(sqlite_driver.db_path)
    events = list(ledger.export_events(account_id="local-journal"))
    confirmed_by_observation = {
        str(event["causation_id"]): str(event["event_id"])
        for event in events
        if event.get("causation_id")
        and isinstance(event.get("provenance"), dict)
        and event["provenance"].get("source") == "tradingview_confirmed"
    }
    observations = []
    for event in events:
        provenance = event.get("provenance")
        if event.get("event_type") != "JournalReviewAdded" or not isinstance(provenance, dict):
            continue
        if provenance.get("source") != "tradingview_webhook":
            continue
        confirmation_event_id = confirmed_by_observation.get(str(event.get("event_id")))
        observation = _observation_from_event(
            event,
            status="CONFIRMED" if confirmation_event_id else "PENDING_REVIEW",
            confirmation_event_id=confirmation_event_id,
        )
        if observation is not None:
            observations.append(observation)
    return {
        "status": "READY",
        "count": min(len(observations), limit),
        "observations": list(reversed(observations[-limit:])),
    }


@webhook_router.post("/tradingview/observations/{observation_id}/confirm")
def confirm_tradingview_observation(
    observation_id: str,
    confirmation: TradingViewObservationConfirmPayload,
):
    """Convert an alert observation into an explicitly confirmed external trade."""
    ledger = EvidenceLedgerRepository(sqlite_driver.db_path)
    event = ledger.get_event(observation_id)
    if not event or event.get("event_type") != "JournalReviewAdded":
        raise HTTPException(status_code=404, detail="TradingView observation not found")
    provenance = event.get("provenance")
    if not isinstance(provenance, dict) or provenance.get("source") != "tradingview_webhook":
        raise HTTPException(status_code=404, detail="TradingView observation not found")
    observation = _observation_from_event(event)
    if observation is None:
        raise HTTPException(status_code=409, detail="TradingView observation payload is unavailable")

    trade_id = f"TV-{observation_id}"
    existing = sqlite_driver.get_trade(trade_id)
    if existing is not None:
        return {"status": "ALREADY_CONFIRMED", "trade": existing, "observation_id": observation_id}

    trade_record = {
        "id": trade_id,
        "symbol": observation["symbol"],
        "side": "BUY" if observation["action"] in ("BUY", "LONG") else "SELL",
        "entry_price": confirmation.entry_price,
        "exit_price": None,
        "qty": observation["qty"],
        "stop_loss": observation.get("stop_loss"),
        "take_profit": observation.get("take_profit"),
        "entry_time": confirmation.entry_time or datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "status": "OPEN",
        "pnl": 0.0,
        "record_mode": "EXTERNAL",
        "execution_venue": confirmation.execution_venue,
        "price_source": "tradingview_alert",
        "price_source_symbol": observation["symbol"],
        "price_status": "UNAVAILABLE",
        "price_observed_at": observation.get("observed_at"),
        "price_origin": "MANUAL",
        "notes": confirmation.notes or f"Confirmed external trade from TradingView alert: {observation['strategy']}",
    }
    trade = sync_pipeline.record_and_sync_trade(
        trade_record,
        source="tradingview_confirmed",
        source_ref=observation_id,
        causation_id=observation_id,
        provenance_extra={
            "record_mode": "EXTERNAL",
            "execution_venue": confirmation.execution_venue,
            "price_source": "tradingview_alert",
            "price_source_symbol": observation["symbol"],
            "price_status": "UNAVAILABLE",
            "price_observed_at": observation.get("observed_at"),
            "price_origin": "MANUAL",
            "review_state": "USER_CONFIRMED",
        },
    )
    return {"status": "CONFIRMED", "observation_id": observation_id, "trade": trade}

@webhook_router.get("/webhook/cloudflare-relay/config")
def get_cloudflare_tunnel_config():
    """Returns instructions and Cloudflare Worker relay script configuration."""
    return {
        "relay_mode": "CLOUDFLARE_TUNNEL_WORKER",
        "webhook_endpoint": f"{settings.gateway_url()}/api/v1/webhook/tradingview",
        "auth_header": "X-TradingView-Signature",
        "secret_configured": WEBHOOK_SECRET_CONFIGURED,
        "auth_required": True,
    }
