"""
TradingView HMAC-SHA256 Webhook & Cloudflare Tunnel Relay Receiver.
Securely verifies, parses, and ingests Pine Script alert signals into Kuantra Terminal.
"""

import hmac
import hashlib
import json
import time
import re
import logging
import os
import secrets
from typing import Dict, Any, Optional
from pydantic import BaseModel
from fastapi import APIRouter, Header, HTTPException, Request
from app.db.sync_pipeline import sync_pipeline
from app.core.config import settings

logger = logging.getLogger("webhook_tv")

webhook_router = APIRouter(tags=["Webhook"])

# Never ship a shared/default secret. In development without explicit configuration,
# use a process-random value so requests fail across restarts; production deployments
# must provide KUANTRA_WEBHOOK_SECRET through an external secret store.
WEBHOOK_SECRET_CONFIGURED = bool(os.environ.get("KUANTRA_WEBHOOK_SECRET"))
WEBHOOK_SECRET_KEY = os.environ.get("KUANTRA_WEBHOOK_SECRET") or secrets.token_urlsafe(32)

class TradingViewSignalPayload(BaseModel):
    symbol: str
    action: str
    price: float
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    qty: Optional[float] = 1.0
    strategy: Optional[str] = "PineScript_Alert"
    timeframe: Optional[str] = "15m"
    passphrase: Optional[str] = None
    timestamp: Optional[float] = None

def verify_hmac_signature(raw_body: bytes, signature_header: Optional[str], secret: str = WEBHOOK_SECRET_KEY) -> bool:
    """Verifies HMAC-SHA256 signature generated by Cloudflare Worker or TradingView."""
    if not signature_header:
        return False
    expected = hmac.new(secret.encode("utf-8"), raw_body, hashlib.sha256).hexdigest()
    return hmac.compare_digest(expected.lower(), signature_header.lower())

def verify_passphrase(provided_passphrase: Optional[str], expected_secret: str = WEBHOOK_SECRET_KEY) -> bool:
    if not provided_passphrase:
        return False
    return hmac.compare_digest(provided_passphrase, expected_secret)

@webhook_router.post("/webhook/tradingview")
async def receive_tradingview_webhook(
    request: Request,
    x_tradingview_signature: Optional[str] = Header(None, alias="X-TradingView-Signature"),
    x_cf_tunnel_auth: Optional[str] = Header(None, alias="X-CF-Tunnel-Auth")
):
    raw_body = await request.body()
    try:
        data = json.loads(raw_body.decode("utf-8"))
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid JSON payload")

    # Security check: verify via HMAC signature OR passphrase
    has_valid_hmac = verify_hmac_signature(raw_body, x_tradingview_signature)
    has_valid_passphrase = verify_passphrase(data.get("passphrase"))
    has_valid_tunnel = x_cf_tunnel_auth == WEBHOOK_SECRET_KEY

    if not (has_valid_hmac or has_valid_passphrase or has_valid_tunnel):
        logger.warning("[WEBHOOK] Unauthorized signal rejected (Invalid HMAC / Passphrase).")
        raise HTTPException(status_code=401, detail="Unauthorized: Invalid HMAC signature or passphrase")

    raw_sym = str(data.get("symbol", "BTCUSDT")).upper()
    symbol = re.sub(r"[^a-zA-Z0-9]", "", raw_sym)
    action = str(data.get("action", "BUY")).upper()
    price = float(data.get("price", 0.0))
    sl = float(data["stop_loss"]) if data.get("stop_loss") else None
    tp = float(data["take_profit"]) if data.get("take_profit") else None
    qty = float(data.get("qty", 1.0))
    strategy = data.get("strategy", "TradingView_Alert")

    logger.info(f"[WEBHOOK] Valid signal received: {action} {qty} {symbol} @ {price}")

    # Process and record signal
    trade_record = {
        "id": f"TV-{int(time.time()*1000)}",
        "symbol": symbol,
        "side": "BUY" if action in ("BUY", "LONG") else "SELL",
        "entry_price": price,
        "exit_price": None,
        "qty": qty,
        "stop_loss": sl,
        "take_profit": tp,
        "entry_time": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "status": "OPEN",
        "pnl": 0.0,
        "notes": f"Ingested from TV Webhook: {strategy}"
    }
    sync_pipeline.record_and_sync_trade(
        trade_record,
        source="tradingview_webhook",
        source_ref=strategy,
    )

    return {
        "status": "RECEIVED",
        "trade_id": trade_record["id"],
        "symbol": symbol,
        "action": action,
        "price": price,
        "timestamp": time.time()
    }

@webhook_router.get("/webhook/cloudflare-relay/config")
def get_cloudflare_tunnel_config():
    """Returns instructions and Cloudflare Worker relay script configuration."""
    return {
        "relay_mode": "CLOUDFLARE_TUNNEL_WORKER",
        "webhook_endpoint": f"{settings.gateway_url()}/api/v1/webhook/tradingview",
        "auth_header": "X-TradingView-Signature",
        "secret_configured": WEBHOOK_SECRET_CONFIGURED,
        "auth_required": True,
    }
