"""
TradingView HMAC-SHA256 Webhook & Cloudflare Tunnel Relay Receiver.
Securely verifies, parses, and ingests Pine Script alert signals into Kuantra Terminal.
"""

import hmac
import hashlib
import json
import math
import time
import re
import logging
import os
import secrets
from typing import Dict, Any, Optional
from pydantic import BaseModel, ConfigDict, Field, ValidationError, field_validator
from fastapi import APIRouter, Header, HTTPException, Request
from app.db.sync_pipeline import sync_pipeline
from app.core.config import settings
from app.core.input_limits import MAX_WEBHOOK_BYTES

logger = logging.getLogger("webhook_tv")

webhook_router = APIRouter(tags=["Webhook"])

# Never ship a shared/default secret. In development without explicit configuration,
# use a process-random value so requests fail across restarts; production deployments
# must provide KUANTRA_WEBHOOK_SECRET through an external secret store.
WEBHOOK_SECRET_CONFIGURED = bool(os.environ.get("KUANTRA_WEBHOOK_SECRET"))
WEBHOOK_SECRET_KEY = os.environ.get("KUANTRA_WEBHOOK_SECRET") or secrets.token_urlsafe(32)

class TradingViewSignalPayload(BaseModel):
    model_config = ConfigDict(extra="ignore", str_strip_whitespace=True)

    symbol: str = Field(..., min_length=1, max_length=64)
    action: str = Field(..., min_length=1, max_length=16)
    price: float = Field(..., gt=0, le=10**15)
    stop_loss: Optional[float] = Field(default=None, gt=0, le=10**15)
    take_profit: Optional[float] = Field(default=None, gt=0, le=10**15)
    qty: Optional[float] = Field(default=1.0, gt=0, le=10**12)
    strategy: Optional[str] = Field(default="PineScript_Alert", max_length=128)
    timeframe: Optional[str] = Field(default="15m", max_length=32)
    passphrase: Optional[str] = Field(default=None, max_length=512)
    timestamp: Optional[float] = Field(default=None, gt=0, le=10**12)

    @field_validator("action", mode="before")
    @classmethod
    def _normalize_action(cls, value: Any) -> str:
        action = str(value or "").strip().upper()
        if action not in {"BUY", "SELL", "LONG", "SHORT"}:
            raise ValueError("action must be BUY, SELL, LONG, or SHORT")
        return action

    @field_validator("strategy", "timeframe", "passphrase")
    @classmethod
    def _reject_control_text(cls, value: Optional[str]) -> Optional[str]:
        if value is not None and any(ord(character) < 32 for character in value):
            raise ValueError("text fields cannot contain control characters")
        return value

def verify_hmac_signature(raw_body: bytes, signature_header: Optional[str], secret: str = WEBHOOK_SECRET_KEY) -> bool:
    """Verifies HMAC-SHA256 signature generated by Cloudflare Worker or TradingView."""
    if not signature_header:
        return False
    expected = hmac.new(secret.encode("utf-8"), raw_body, hashlib.sha256).hexdigest()
    return hmac.compare_digest(expected.lower(), signature_header.lower())

def verify_passphrase(provided_passphrase: Optional[str], expected_secret: str = WEBHOOK_SECRET_KEY) -> bool:
    if not provided_passphrase:
        return False
    return hmac.compare_digest(provided_passphrase, expected_secret)

@webhook_router.post("/webhook/tradingview")
async def receive_tradingview_webhook(
    request: Request,
    x_tradingview_signature: Optional[str] = Header(None, alias="X-TradingView-Signature"),
    x_cf_tunnel_auth: Optional[str] = Header(None, alias="X-CF-Tunnel-Auth")
):
    content_length = request.headers.get("content-length")
    if content_length:
        try:
            if int(content_length) > MAX_WEBHOOK_BYTES:
                raise HTTPException(
                    status_code=413,
                    detail=f"Webhook body exceeds the safety size limit of {MAX_WEBHOOK_BYTES} bytes.",
                )
        except ValueError as exc:
            raise HTTPException(status_code=400, detail="Invalid Content-Length header") from exc

    raw_body = await request.body()
    if len(raw_body) > MAX_WEBHOOK_BYTES:
        raise HTTPException(
            status_code=413,
            detail=f"Webhook body exceeds the safety size limit of {MAX_WEBHOOK_BYTES} bytes.",
        )
    try:
        data = json.loads(raw_body.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise HTTPException(status_code=400, detail="Invalid UTF-8 JSON payload") from exc
    if not isinstance(data, dict):
        raise HTTPException(status_code=400, detail="Webhook JSON root must be an object")

    # Security check: verify via HMAC signature OR passphrase
    has_valid_hmac = verify_hmac_signature(raw_body, x_tradingview_signature)
    has_valid_passphrase = verify_passphrase(data.get("passphrase"))
    has_valid_tunnel = x_cf_tunnel_auth == WEBHOOK_SECRET_KEY

    if not (has_valid_hmac or has_valid_passphrase or has_valid_tunnel):
        logger.warning("[WEBHOOK] Unauthorized signal rejected (Invalid HMAC / Passphrase).")
        raise HTTPException(status_code=401, detail="Unauthorized: Invalid HMAC signature or passphrase")

    try:
        payload = TradingViewSignalPayload.model_validate(data)
    except ValidationError as exc:
        raise HTTPException(status_code=400, detail="Invalid TradingView signal payload") from exc

    if not all(
        math.isfinite(number)
        for number in (payload.price, payload.qty, payload.stop_loss, payload.take_profit, payload.timestamp)
        if number is not None
    ):
        raise HTTPException(status_code=400, detail="Signal numeric fields must be finite")

    raw_sym = payload.symbol.upper()
    symbol = re.sub(r"[^a-zA-Z0-9]", "", raw_sym)
    if not symbol or len(symbol) > 64:
        raise HTTPException(status_code=400, detail="Signal symbol is invalid")
    action = payload.action
    price = payload.price
    sl = payload.stop_loss
    tp = payload.take_profit
    qty = payload.qty or 1.0
    strategy = payload.strategy or "TradingView_Alert"

    logger.info(f"[WEBHOOK] Valid signal received: {action} {qty} {symbol} @ {price}")

    # Process and record signal
    trade_record = {
        "id": f"TV-{int(time.time()*1000)}",
        "symbol": symbol,
        "side": "BUY" if action in ("BUY", "LONG") else "SELL",
        "entry_price": price,
        "exit_price": None,
        "qty": qty,
        "stop_loss": sl,
        "take_profit": tp,
        "entry_time": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "status": "OPEN",
        "pnl": 0.0,
        "notes": f"Ingested from TV Webhook: {strategy}"
    }
    sync_pipeline.record_and_sync_trade(
        trade_record,
        source="tradingview_webhook",
        source_ref=strategy,
    )

    return {
        "status": "RECEIVED",
        "trade_id": trade_record["id"],
        "symbol": symbol,
        "action": action,
        "price": price,
        "timestamp": time.time()
    }

@webhook_router.get("/webhook/cloudflare-relay/config")
def get_cloudflare_tunnel_config():
    """Returns instructions and Cloudflare Worker relay script configuration."""
    return {
        "relay_mode": "CLOUDFLARE_TUNNEL_WORKER",
        "webhook_endpoint": f"{settings.gateway_url()}/api/v1/webhook/tradingview",
        "auth_header": "X-TradingView-Signature",
        "secret_configured": WEBHOOK_SECRET_CONFIGURED,
        "auth_required": True,
    }
